Convert folder checks to string in file management
Fixes the error (in versions of WebUI Forge Neo as of 2026-05-23):
---
File "D:\StabilityMatrix\Data\Packages\forge-neo\extensions\sd-civitai-browser-neo\scripts\civitai_file_manage.py", line 883, in _detect_content_type_from_path
    if folder and file_path.startswith(folder):
                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: startswith first arg must be str or a tuple of str, not WindowsPath
---

Tested locally in my WebUI Forge Neo installation (via StabilityMatrix on Windows)